name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # ১.২১.১ এর NMS লাইব্রেরিগুলো লোকাল রানারে অটোমেটিক বিল্ড করার অফিশিয়াল মেথড
      - name: Run BuildTools for Spigot NMS
        run: |
          mkdir buildtools && cd buildtools
          curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          java -jar BuildTools.jar --rev 1.21.1 --remapped

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MrSusu-Plugin
          path: target/MrSusu-1.0.0.jar
